[package]
name = "simple-redis"
version = "0.1.0"
authors = ["Ethan <liu.zy.ethan@gmail.com>"]
edition = "2021"
license = "MIT or Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enum_dispatch = "0.3.13"
